files:
  include: src/scss/**/*.scss
rules:
  class-name-format:
    - 1
    - allow-leading-underscore: false
      convention: strictbem
  indentation:
    - 1
    - size: tab
  quotes:
    - 1
    - style: double
  border-zero: 0
  nesting-depth:
    - 1
    - max-depth: 4
  no-color-literals: 0
  leading-zero:
    - 1
    - include: true
